### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by yumenglong** [fex-team/fis-parser-node-sass#19]
G:\xampphtdocs\LFFworkSpace\A-new-React-flux-require\router-basic-demo>npm install fis-parser-node-sass -g
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

> spawn-sync@1.0.15 postinstall C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall
## 

> node-sass@3.4.2 install C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/win32-x64-46_binding.node":

read ECONNRESET

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

```
  export HTTP_PROXY=http://example.com:1234
```

or configure npm proxy via

```
  npm config set proxy http://example.com:8080
```

> node-sass@3.4.2 postinstall C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass
> node scripts/build.js

Building: G:\program files\nodejs\node.exe C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'G:\program files\nodejs\node.exe',
gyp verb cli   'C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.3.1
gyp info using node@4.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory

gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.3.1
gyp info using node@4.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:63:19)
gyp verb `which` failed     at E (C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:72:29)
gyp verb `which` failed     at C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:81:16
gyp verb `which` failed     at C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python2 [Error: not found: python2]
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at F (C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:63:19)
gyp verb `which` failed     at E (C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:72:29)
gyp verb `which` failed     at C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:81:16
gyp verb `which` failed     at C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python [Error: not found: python]
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "G:\program files\nodejs\node.exe" "C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\cp\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "G:\program files\nodejs\node.exe" "G:\program files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "fis-parser-node-sass" "-g"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\xampphtdocs\LFFworkSpace\A-new-React-flux-require\router-basic-demo\npm-debug.log

**Comment by 2betop** [comment]
Try `cnpm install fis-parser-node-sass -g`

**Comment by yumenglong** [comment]
C:\Users\cp>cnpm install fis-parser-node-sass -g
[npmconf@2.1.2] deprecate: this package has been reintegrated into npm and is no
w out of date with respect to npm
[lodash@1.0.2] deprecate: lodash@<3.0.0 is no longer maintained. Upgrade to loda
sh@^4.0.0.
[graceful-fs@1.2.3] deprecate: graceful-fs version 3 and before will fail on new
er node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
[fis-parser-node-sass@*] installed at node_modules.fis-parser-node-sass_npminst
all\fis-parser-node-sass\0.1.9\fis-parser-node-sass (0 packages, use 40s, speed
105.89kB/s, json 1.29MB, tarball 2.85MB)
excute post install scripts...
[spawn-sync@1.0.15] scripts.postinstall: "node postinstall" at C:\Users\cp\AppDa
ta\Roaming\npm\node_modules.fis-parser-node-sass_npminstall\spawn-sync\1.0.15\s
pawn-sync
[spawn-sync@1.0.15] scripts.postinstall success, use 173ms
[node-sass@3.4.2] scripts.install: "node scripts/install.js" at C:\Users\cp\AppD
ata\Roaming\npm\node_modules.fis-parser-node-sass_npminstall\node-sass\3.4.2\no
de-sass
Binary downloaded and installed at C:\Users\cp\AppData\Roaming\npm\node_modules\
.fis-parser-node-sass_npminstall\node-sass\3.4.2\node-sass\vendor\win32-x64-46\b
inding.node
[node-sass@3.4.2] scripts.install success, use 13s
[node-sass@3.4.2] scripts.postinstall: "node scripts/build.js" at C:\Users\cp\Ap
pData\Roaming\npm\node_modules.fis-parser-node-sass_npminstall\node-sass\3.4.2\
node-sass
`C:\Users\cp\AppData\Roaming\npm\node_modules\.fis-parser-node-sass_npminstall\
node-sass\3.4.2\node-sass\vendor\win32-x64-46\binding.node` exists.
 testing binary.
Binary is fine; exiting.
[node-sass@3.4.2] scripts.postinstall success, use 457ms
All packages installed (196 packages installed from npm registry, use 54s, speed
 78.73kB/s, json 230(1.29MB), tarball 2.85MB)

这样算是安装成功了吗？

**Comment by 2betop** [comment]
嗯，应该是成功了

**Comment by yumenglong** [comment]
恩 谢谢
