### ISSUE TITLE
请问需要安装python?

### ISSUE THREAD

**Issue by xiegqooo** [fex-team/fis-parser-node-sass#2]
E:\t>npm install fis-parser-node-sass -g
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"
})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4
.28"})
npm WARN engine boom@2.9.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"}
## )

> thread-sleep@1.0.4 install C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_modules\fis-parser-no
> de-sass\node_modules\node-sass\node_modules\cross-spawn\node_modules\spawn-sync\node_modules\try-thr
> ead-sleep\node_modules\thread-sleep
> node-pre-gyp install --fallback-to-build

[thread-sleep] Success: "C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_modules\fis-parser-node-s
ass\node_modules\node-sass\node_modules\cross-spawn\node_modules\spawn-sync\node_modules\try-thread-
sleep\node_modules\thread-sleep\lib\binding\Release\node-v11-win32-x64\thread_sleep.node" is install
ed via remote

> spawn-sync@1.0.13 postinstall C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_modules\fis-parser
> -node-sass\node_modules\node-sass\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall
> 
> node-sass@3.3.3 install C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_modules\fis-parser-node-
> sass\node_modules\node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.3/win32-x64-11_binding.nod
e": connect ETIMEDOUT

> node-sass@3.3.3 postinstall C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_modules\fis-parser-n
> ode-sass\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files (x86)\nodejs\node.exe C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_m
odules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --v
erbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\Program Files (x86)\nodejs\node.exe',
gyp verb cli   'C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_modules\fis-parser-node-sas
s\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.0.3
gyp info using node@0.10.33 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_modules\fis-pars
er-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:78:19)
gyp verb `which` failed     at E (C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_modules\fis-pars
er-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:82:29)
gyp verb `which` failed     at C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_modules\fis-parser-
node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:93:16
gyp verb `which` failed     at Object.oncomplete (fs.js:107:15)
gyp verb `which` failed  python2 [Error: not found: python2]
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at F (C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_modules\fis-pars
er-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:78:19)
gyp verb `which` failed     at E (C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_modules\fis-pars
er-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:82:29)
gyp verb `which` failed     at C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_modules\fis-parser-
node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:93:16
gyp verb `which` failed     at Object.oncomplete (fs.js:107:15)
gyp verb `which` failed  python [Error: not found: python]
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_modules\fis-pa
rser-node-sass\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_modules\fis-parser-node-sass
\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Users\xiegqooo_f0s0r9\AppData\R
oaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\bi
n\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--l
ibsass_library="
gyp ERR! cwd C:\Users\xiegqooo_f0s0r9\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_mod
ules\node-sass
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed

npm ERR! node-sass@3.3.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.3.3 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\nod
e_modules\npm\bin\npm-cli.js" "install" "fis-parser-node-sass" "-g"
npm ERR! cwd E:\t
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by zhangtao07** [comment]
默认安装容易被墙，建议用 cnpm 安装
