### ISSUE TITLE
jello编译报错找不到 ../functions

### ISSUE THREAD

**Issue by qiaosang** [fex-team/fis-parser-node-sass#7]
-bash-4.1# jello release

 Ω .........../apps/node-v4.2.2-linux-x64/lib/node_modules/fis-parser-node-sass/index.js:144
            throw new Error('Can\'t find `' + prev +'`');
            ^

Error: Can't find `../functions`
    at Object.opts.importer (/apps/node-v4.2.2-linux-x64/lib/node_modules/fis-parser-node-sass/index.js:144:19)
    at options.importer (/apps/node-v4.2.2-linux-x64/lib/node_modules/fis-parser-node-sass/node_modules/node-sass/lib/index.js:387:31)
    at Object.module.exports.renderSync (//apps/node-v4.2.2-linux-x64/lib/node_modules/fis-parser-node-sass/node_modules/node-sass/lib/index.js:410:23)
    at module.exports (/apps/node-v4.2.2-linux-x64/lib/node_modules/fis-parser-node-sass/index.js:191:20)
    at /apps/node-v4.2.2-linux-x64/lib/node_modules/jello/node_modules/fis/node_modules/fis-kernel/lib/compile.js:329:26
    at /apps/node-v4.2.2-linux-x64/lib/node_modules/jello/node_modules/fis/node_modules/fis-kernel/lib/util.js:711:17
    at Array.forEach (native)
    at Function._.pipe (/apps/node-v4.2.2-linux-x64/lib/node_modules/jello/node_modules/fis/node_modules/fis-kernel/lib/util.js:698:20)
    at pipe (/apps/node-v4.2.2-linux-x64/lib/node_modules/jello/node_modules/fis/node_modules/fis-kernel/lib/compile.js:324:14)
    at process (/apps/node-v4.2.2-linux-x64/lib/node_modules/jello/node_modules/fis/node_modules/fis-kernel/lib/compile.js:298:9)

**Comment by qiaosang** [comment]
compass-mixins/compass/functions  不知道怎么会用到   自己的css里没有引用functions

**Comment by 2betop** [comment]
升级最新  fis-parser-node-sass 试试吧，我貌似也遇到过，不过我升级 importer 逻辑后就好了。

**Comment by qiaosang** [comment]
请教下怎么升级  importer 逻辑

**Comment by 2betop** [comment]
你升级到最新的 `fis-parser-node-sass` 就可以了，good luck!

**Comment by qiaosang** [comment]
[ERROR] load plugin [fis-parser-node-sass] error : The `libsass` binding was not found in /apps/node-v4.2.3-linux-x64/lib/node_modules/fis-parser-node-sass/node_modules/node-sass/vendor/linux-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.

求解决 ，报错了

**Comment by qiaosang** [comment]
运行了 npm rebuild node-sass  不起作用

**Comment by 2betop** [comment]
npm rebuild 估计你得进入 fis-parser-node-sass 目录执行，不知道你是在什么目录下执行的

**Comment by qiaosang** [comment]
是在fis-parser-node-sass目录下执行的，报警告

-bash-4.1# ls
compile.js  index.js  LICENSE.md  node_modules  package.json  README.md
-bash-4.1# npm rebuild node-sass

npm WARN cannot run in wd node-sass@3.4.2 node scripts/install.js (wd=/apps/node-v4.2.3-linux-x64/lib/node_modules/fis-parser-node-sass/node_modules/node-sass)

npm WARN cannot run in wd node-sass@3.4.2 node scripts/build.js (wd=/apps/node-v4.2.3-linux-x64/lib/node_modules/fis-parser-node-sass/node_modules/node-sass)

node-sass@3.4.2 /apps/node-v4.2.3-linux-x64/lib/node_modules/fis-parser-node-sass/node_modules/node-sass

**Comment by qiaosang** [comment]
不知道 是不是 版本问题
-bash-4.1# node -v
v4.2.3
-bash-4.1# npm -v
2.14.7

**Comment by 2betop** [comment]
sudo 跑貌似有这个问题，试试加下面 flag
`sudo npm rebuild --unsafe-perm`

**Comment by qiaosang** [comment]
恩 加上参数后不报上面的错误了 报这个了

[ERROR] ../src/Image.cc:317 Unknow format

**Comment by qiaosang** [comment]
恩 加上参数后不报上面的错误了 报这个了

[ERROR] ../src/Image.cc:317 Unknow format

**Comment by 2betop** [comment]
这个应该不是 node-sass  的错误了，应该是你什么图片的格式不对引起的。

**Comment by qiaosang** [comment]
只有 png、gif格式的图片格式，  Image.cc 是那个库里的开源代码 不知道
